language: generic
compiler:
  - clang
  - gcc
dist: xenial
sudo: required
before_install:
- sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list' 
- sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
- sudo apt-get update -qq
- sudo apt-get install -qq ros-kinetic-desktop ros-kinetic-catkin python-catkin-pkg
before_script:
- source /opt/ros/kinetic/setup.bash
- mkdir -p ~/catkin_ws/src
- catkin_init_workspace ~/catkin_ws/src
- ln -s "$(pwd)" ~/catkin_ws/src/rviz_plugin_covariance
- cd ~/catkin_ws
script:
- catkin_make
after_success:
- source ~/catkin_ws/devel/setup.bash
